export default ({ env }) => ({
  upload: {
    config: {
      provider: "cloudinary",
      providerOptions: {
        cloud_name: env("CLOUDINARY_NAME"),
        api_key: env("CLOUDINARY_KEY"),
        api_secret: env("CLOUDINARY_SECRET"),
      },
      actionOptions: {
        upload: {},
        delete: {},
      },
    },
  },
  "google-maps": {
    enabled: true,
  },
  navigation: {
    enabled: true,
    config: {
      contentTypes: [
        'api::article.article',
        'api::manual.manual',
        'api::group.group',
        'api::rental-location.rental-location',
        'api::articles-page.articles-page',
        'api::contact-page.contact-page',
        'api::cookie-policy-page.cookie-policy-page',
        'api::drugs-alcohol-policy-page.drugs-alcohol-policy-page',
        'api::groups-page.groups-page',
        'api::home-page.home-page',
        'api::info-page.info-page',
        'api::manuals-overview-page.manuals-overview-page',
        'api::privacy-policy-page.privacy-policy-page',
        'api::register-page.register-page',
        'api::rental-page.rental-page',
      ],
      defaultContentTypes: ['api::article.article'],
      contentTypesNameFields: {
        'api::article.article': ['pageTitle'],
        'api::manual.manual': ['title'],
        'api::group.group': ['pageTitle'],
        'api::rental-location.rental-location': ['pageTitle'],
        'api::articles-page.articles-page': ['title'],
        'api::contact-page.contact-page': ['title'],
        'api::cookie-policy-page.cookie-policy-page': ['title'],
        'api::drugs-alcohol-policy-page.drugs-alcohol-policy-page': ['title'],
        'api::groups-page.groups-page': ['title'],
        'api::home-page.home-page': ['title'],
        'api::info-page.info-page': ['title'],
        'api::manuals-overview-page.manuals-overview-page': ['title'],
        'api::privacy-policy-page.privacy-policy-page': ['title'],
        'api::register-page.register-page': ['title'],
        'api::rental-page.rental-page': ['title'],
      },
      pathDefaultFields: {
        'api::article.article': ['slug'],
        'api::manual.manual': ['slug'],
        'api::group.group': ['slug'],
        'api::rental-location.rental-location': ['slug'],
        'api::articles-page.articles-page': ['slug'],
        'api::contact-page.contact-page': ['slug'],
        'api::cookie-policy-page.cookie-policy-page': ['slug'],
        'api::drugs-alcohol-policy-page.drugs-alcohol-policy-page': ['slug'],
        'api::groups-page.groups-page': ['slug'],
        'api::home-page.home-page': ['slug'],
        'api::info-page.info-page': ['slug'],
        'api::manuals-overview-page.manuals-overview-page': ['slug'],
        'api::privacy-policy-page.privacy-policy-page': ['slug'],
        'api::register-page.register-page': ['slug'],
        'api::rental-page.rental-page': ['slug'],
      },
      allowedLevels: 2,
    },
  },
});
